- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorControllerTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sscs/CallbackOrchestratorTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/ServiceTokenGeneratorConfiguration.java
- src/main/java/uk/gov/hmcts/reform/sscs/Application.java
- src/main/java/uk/gov/hmcts/reform/sscs/config/ServiceTokenGeneratorConfiguration.java
- src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorController.java
A possible spring authentication fix.
While viewing on multiple projects. They all seem to have this nugget of spring configuration for authentication. 
* Added a functional test that will authenticate using idam (!?)
* Included sscs-commons as a test dependency.
* Upgraded checkstyle to avoid a security vulnerability.
> SSCS-5166 - Spring Authentication fix.

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- README.md
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/SSCS-5209
```
[ ] Yes
[x] No
```
> Configure for Jenkins pipeline

- src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java
> spring autowire fix

- build.gradle
> SSCS-3936 Upgrade java logging

- Dockerfile
- Jenkinsfile_parameterized
- build.gradle
- config/owasp/suppressions.xml
- infrastructure/main.tf
- kubernetes/deployment.template.yaml
- src/main/resources/application.yaml
suppress CVE-2019-3795
run dependency check once.
ensure correct deployment to AKS.
This is blocking other PR's here.
> get the sscs-ccd-callback-orchestrator pipeline working

- infrastructure/main.tf
Alter aat values for azure service bus.
Correct topic name and the subscription name.
> Alter aat values for azure service bus

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-6063
> Bump QPID JMS library version to 0.44.0

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-6161
Fix build pipeline issue
```
[ ] Yes
[X] No
```
> SSCS-6161 - fix build pipeline issue

- src/integrationTest/java/uk/gov/hmcts/reform/sscs/servicebus/TopicJmsTest.java
- src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicPublisher.java
- src/test/java/uk/gov/hmcts/reform/sscs/servicebus/TopicPublisherTest.java
> SSCS-6138 Evidence share – Exception from the queue

- Jenkinsfile_CNP
> remove deprecated config

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-6476
Update sscs-common candidate version
```
[ ] Yes
[X] No
```
> SSCS-6476 - update sscs-common release version

- build.gradle
- config/owasp/suppressions.xml
fix sonar
```
[ ] Yes
[x] No
```
>  fix build

- .github/renovate.json
- build.gradle
- charts/sscs-ccd-callback-orchestrator/Chart.yaml
- charts/sscs-ccd-callback-orchestrator/requirements.yaml
SSCS-7587 - Upgrade java chart. Add renovate
> SSCS-7587 - Upgrade java chart. Add renovate

- charts/sscs-ccd-callback-orchestrator/Chart.yaml
- charts/sscs-ccd-callback-orchestrator/values.yaml
> SSCS-7587 - Add readiness health path

- Dockerfile
- build.gradle
> SSCS-7800 - Upgrade to Java 11

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-7535
```
[ ] Yes
[X] No
```
> SSCS-7535 up common for isScottish

- build.gradle
- config/owasp/suppressions.xml
> WLA-735: Update commons

- src/integrationTest/java/uk/gov/hmcts/reform/sscs/servicebus/TopicJmsTest.java
- src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorController.java
- src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicPublisher.java
- src/test/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorControllerTest.java
- src/test/java/uk/gov/hmcts/reform/sscs/servicebus/TopicPublisherTest.java
> SSCS-8224 log messageId after publish

- .github/renovate.json
- src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorController.java
> fix the build after the gradle upgrade

- config/owasp/suppressions.xml
> Suppress tomcat package

- security.sh
> added folder for reporting

- src/main/java/uk/gov/hmcts/reform/sscs/servicebus/TopicPublisher.java
> SSCS-8118: added extra logs

- build.gradle
> dependency check resolution for CVE-2020-8908

- build.gradle
change the repositories section around
> change the repositories section around

- build.gradle
SSCS-8684 - Upgrade Idam Client Only
> SSCS-8684 - Upgrade Idam Client Only

- build.gradle
> fixed depenendency check

- build.gradle
> upgraded tomcat version to fix dependency check

- build.gradle
> Update commons-io version to fix dc failures

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
Finish move to jitpack
```
[ ] Yes
[x] No
```
> sscs 9066 move to jitpack

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
m0ve to release
```
[ ] Yes
[x] No
```
> sscs 9066 move to release

- audit.json
> Supress warnings, ticket raised to action

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-8808
https://tools.hmcts.net/jira/browse/SSCS-8933
```
[ ] Yes
[ ] No
```
> SSCS-8808: IIDB (SYA)- Update: Check your answers page

- build.gradle
> SSCS-9122 upgrade common

- build.gradle
updated common with social fund benefit
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9061](url)
> SSCS-9061-updated common with social fund benefit

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/SSCS-9381
The changes are in this PR but the same are implemented on nightly branch
```
[ ] Yes
[ x] No
```
> SSCS-9381: Enable fortify scan for nightly build

- Jenkinsfile_nightly
- build.gradle
enabled and added config for mutation tests
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9271](url)
> SSCS-9271-added mutation tests

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9429
> SSCS-9429 Deserialize case type id

- config/owasp/suppressions.xml
> suppress spring dependency check until version upgraded

- config/owasp/suppressions.xml
CVE-2021-22096-fix
```
[ ] Yes
[ x] No
```
> spring dependency check modified

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackOrchestratorController.java
https://tools.hmcts.net/jira/browse/SSCS-9743
```
[ ] Yes
[ ] No
```
> SSCS-9743:Child Support - otherPartyAdded Notification

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9890
```
[ ] Yes
[ ] No
```
> Upgrade log4j to 2.16.0

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10129
```
[ ] Yes
[X] No
```
> surppress dependencies

- charts/sscs-ccd-callback-orchestrator/Chart.yaml
https://tools.hmcts.net/jira/browse/SSCS-10137
```
[ ] Yes
[X] No
```
> upgrade helm chart

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10070
update sscs-common version
```
[ ] Yes
[ ] No
```
> update sscs-common version

- build.gradle
> upgrading log4j to 2.17.1

- charts/sscs-ccd-callback-orchestrator/Chart.yaml
https://tools.hmcts.net/jira/browse/SSCS-10236
```
[ ] Yes
[X] No
```
> SSCS-10236 updating helm chart versions

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10280
```
[ ] Yes
[X] No
```
> SSCS-10280: suppressing dependencies

- build.gradle
> SSCS Commons 4.7.1 Upgrade

- build.gradle
- config/owasp/suppressions.xml
> 10376 upgrade branch

- build.gradle
> Don't allow miss match versions

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10146
Update sscs-common version for ticket 10146
```
[ ] Yes
[ ] No
```
> sscs-10146 update sscs-common RC version

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10387
```
[ ] Yes
[x] No
```
> SSCS-10387 Update Commons

- build.gradle
> SSCS-10223 Model bump

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10388
```
[x] Yes
[ ] No
```
> SSCS-10388 Update Commons

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10552
```
[ ] Yes
[X] No
```
> SSCS-10552: upgrade tomcat

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10561
```
[ ] Yes
[X] No
```
> SSCS-10561: Updating spring and suppressions

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10178
```
[ ] Yes
[x] No
```
> SSCS-10178 Commons Bump

- charts/sscs-ccd-callback-orchestrator/Chart.yaml
sscsBaseChartUpdate-Java401
```
[ ] Yes
[ ] No
```
>  sscsBaseChartUpdate-Java401

- config/owasp/suppressions.xml
> extend-suppression-dates

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10805
```
[ ] Yes
[ ] No
```
> SSCS-10805-jar-version-update

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10818
```
[ ] Yes
[x] No
```
> SSCS-10818 Commons Bump

- .github/renovate.json
> SSCS-10901 Fix renovate json

- build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10882
```
[ ] Yes
[x] No
```
> SSCS-10882 Fixing Conflicting IDs

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10985
```
[ ] Yes
[x] No
```
> SSCS-10985 CVE Fix Commons Bump

- charts/sscs-ccd-callback-orchestrator/Chart.yaml
- charts/sscs-ccd-callback-orchestrator/values.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/SSCS-10924
> SSCS-10924 Move to tf managed secret.

- build.gradle
- config/owasp/suppressions.xml
> SSCS-11169 - upgrade jackson-databind and cve-suppression

- build.gradle
> upgrade renovate

- build.gradle
- charts/sscs-ccd-callback-orchestrator/Chart.yaml
- gradle/wrapper/gradle-wrapper.properties
> Upgrade and suppress v3

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/SSCS-11419
```
[ ] Yes
[ ] No
```
> Update repo infrastructure variable remove ilbIp

- config/owasp/suppressions.xml
> Updating CVE suppressions

- Dockerfile
- config/owasp/suppressions.xml
> Fixing pipeline

- Jenkinsfile_nightly
Jenkins file update with afterSuccess
```
[ ] Yes
[x] No
```
> Jenkins file update with afterSuccess

- audit.json
Suppress Security Scan Issue
```
[ ] Yes
[x] No
```
> Suppress Security Scan Issue

- config/owasp/suppressions.xml
> Suppress dependencies

- config/owasp/suppressions.xml
CVE Fix - 08.06.2023
```
[ ] Yes
[x] No
```
> CVE Fix - 08.06.2023

- config/owasp/suppressions.xml
CVE Suppression - 12.06.2023
```
[ ] Yes
[x] No
```
> CVE Suppression - 12.06.2023

- config/owasp/suppressions.xml
CVE Fix - 27.06.23
```
[ ] Yes
[x] No
```
> CVEFix - 27.06.23

- build.gradle
- config/owasp/suppressions.xml
CVE Fix - 03.07.23
```
[ ] Yes
[x] No
```
> CVE Fix - 03.07.23

- build.gradle
CVE Fix - 31.07.23
```
[ ] Yes
[x] No
```
> CVEFix - 31.07.23

- charts/sscs-ccd-callback-orchestrator/Chart.yaml
- charts/sscs-ccd-callback-orchestrator/values.yaml
> Java 17 secret fix

- Dockerfile
- build.gradle
- charts/sscs-ccd-callback-orchestrator/Chart.yaml
- charts/sscs-ccd-callback-orchestrator/values.yaml
- lib/AI-Agent.xml
- lib/applicationinsights.json
- src/main/java/uk/gov/hmcts/reform/sscs/config/SwaggerConfiguration.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/sscs/service/AuthorisationServiceTest.java
> revert - java 17

- build.gradle
- config/owasp/suppressions.xml
CVEFix - 04.08.23
```
[ ] Yes
[x] No
```
> CVEFix - 04.08.23

- audit.json
https://tools.hmcts.net/jira/browse/SSCSCI-12
update audit.json
```
[ ] Yes
[ X] No
```
> security-fix-12092023

- .github/renovate.json
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-12
```
[ ] Yes
[ X] No
```
> update renovate and suppressions

- config/owasp/suppressions.xml
Update suppressions file with new cve
> SSCS - Update Suppressions 

- audit.json
> Security Fix 01.12.2023 

- config/owasp/suppressions.xml
> SSCS - Update suppressions

- config/owasp/suppressions.xml
update suppressions
```
[ ] Yes
[X] No
```
> CVE Fix-22.01.2024
